spring.application.name=backend

# 🌐 Configuração do banco de dados PostgreSQL
# spring.datasource.url=jdbc:postgresql://localhost:5432/araplac
# spring.datasource.username=postgres
# spring.datasource.password=491273
# spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# 🛠️ JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
